### ISSUE TITLE
show_blockp is not declared

### ISSUE THREAD

**Issue by scaryuncledevin** [rynehager/R003_weather_on_gesture#3]
show_blockp on line 158 in main.c is not declared in the local or global scope.

**Comment by rynehager** [comment]
Indeed, I cut and paste that bit, the handle_acell_tap, so I could try to see if I can change it for my use case. Removed the offending parts.

**Comment by scaryuncledevin** [comment]
Where is the commit for the removal of the offending parts?

**Comment by rynehager** [comment]
Pushed.

**Comment by scaryuncledevin** [comment]
Issue has been resolved with b65f01c07e8360f02b6af9f0f9bcd98a0536e0db
