### ISSUE TITLE
Devin has poopy pants

### ISSUE THREAD

**Issue by rynehager** [rynehager/R003_weather_on_gesture#4]
@scaryuncledevin
static void deinit_devinspoopypants();

**Comment by scaryuncledevin** [comment]
Changed my pants, washing poopy pair. Will report back when wash cycle is complete.

**Comment by scaryuncledevin** [comment]
Pants cycle is complete.

**Comment by scaryuncledevin** [comment]
WHY CAN'T I CLOSE THIS ISSUE?

**Comment by rynehager** [comment]
YOU ARE NOT MAINTAINER.

**Comment by rynehager** [comment]
YOU AM NOW MAINTAINER.
